# Generated by Django 4.2.4 on 2023-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
